# Generated by Django 5.0.2 on 2024-02-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_1',
            field=models.CharField(max_length=50, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_2',
            field=models.CharField(max_length=50, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombre_1',
            field=models.CharField(max_length=50, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombre_2',
            field=models.CharField(max_length=50, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='apellido_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='apellido_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='nombre_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='nombre_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo nombre'),
        ),
    ]
